language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - '6'

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: 'Tests'
      name: 'Tests'
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test
        - yarn test:node

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Additional Tests'
      env: EMBER_TRY_SCENARIO=minimum-ember-version
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
